version: '3'
networks:
  micros:
    external: true
services:
  consumer:
    networks:
      - micros
    build:
      context: consumer
  producer:
    networks:
      - micros
    build:
      context: producer
    ports:
      - 9501:9501